#!/usr/bin/env python3
"""Helpers for slide-library/ — the topic-sorted store of reusable slides.

  index                    regenerate slide-library/INDEX.md from library: frontmatter
  use <lib-path> <deck>    copy a library slide + its images into a deck, ready to include

Slidev's `src:` include only resolves paths INSIDE the deck directory -- a `../` path
pointing at slide-library/ is dropped silently, with no warning and no error. So `use`
copies the slide into <deck>/pages/ and prints the include block to paste.

See CLAUDE.md section 8 for the archiving workflow.
"""
import os
import re
import shutil
import sys
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LIBRARY = os.path.join(ROOT, "slide-library")
ASSETS = os.path.join(LIBRARY, "_assets")


def _scalar(value):
    value = value.strip()
    if value.startswith("[") and value.endswith("]"):
        return [v.strip().strip("'\"") for v in value[1:-1].split(",") if v.strip()]
    return value.strip("'\"")


def read_meta(path):
    """Pull the `library:` block out of the first slide's frontmatter.

    Deliberately a small hand-rolled parser rather than a PyYAML dependency:
    the block is always a flat map of scalars and inline lists.
    """
    with open(path, encoding="utf-8") as handle:
        text = handle.read()
    match = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    if not match:
        return None
    meta, inside = {}, False
    for line in match.group(1).splitlines():
        if re.match(r"^library:\s*$", line):
            inside = True
            continue
        if inside:
            if not line.startswith((" ", "\t")):
                break
            entry = re.match(r"^\s+([A-Za-z_][\w-]*):\s*(.*)$", line)
            if entry:
                meta[entry.group(1)] = _scalar(entry.group(2))
    return meta or None


def iter_library():
    for dirpath, dirnames, filenames in os.walk(LIBRARY):
        dirnames[:] = [d for d in dirnames if not d.startswith("_")]
        for name in sorted(filenames):
            if not name.endswith(".md") or name in ("INDEX.md", "README.md"):
                continue
            path = os.path.join(dirpath, name)
            meta = read_meta(path)
            if meta:
                yield os.path.relpath(path, LIBRARY), meta


def cmd_index():
    # slide-library/ is gitignored, so a fresh clone does not have it yet.
    os.makedirs(ASSETS, exist_ok=True)
    by_topic = defaultdict(list)
    count = 0
    for relpath, meta in iter_library():
        topic = meta.get("topic") or os.path.dirname(relpath) or "uncategorised"
        by_topic[topic].append((relpath, meta))
        count += 1

    lines = [
        "# Slide library index",
        "",
        "Generated by `python3 tools/slide_library.py index` — do not edit by hand.",
        "",
        "Pull a slide into a deck with `---` / `src: ../slide-library/<path>` / `---`,",
        "then copy its images across with `slide_library.py use <path> <deck>`.",
        "",
    ]
    for topic in sorted(by_topic):
        lines += ["## " + topic, ""]
        # newest first, so the most recent version of a figure is the obvious pick
        entries = sorted(by_topic[topic], key=lambda e: str(e[1].get("created", "")), reverse=True)
        lines += ["| Created | Slide | From | Tags |", "|---|---|---|---|"]
        for relpath, meta in entries:
            tags = meta.get("tags") or []
            tags = ", ".join(tags) if isinstance(tags, list) else str(tags)
            lines.append("| {} | [{}]({}) | {} | {} |".format(
                meta.get("created", "?"),
                meta.get("title", os.path.basename(relpath)),
                relpath,
                meta.get("source", "?"),
                tags,
            ))
        lines.append("")

    if not count:
        lines += ["_Empty. Archive a slide to populate this index._", ""]

    with open(os.path.join(LIBRARY, "INDEX.md"), "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))
    print("indexed {} slide file(s) across {} topic(s)".format(count, len(by_topic)))


def cmd_use(relpath, deck):
    source = os.path.join(LIBRARY, relpath)
    if not os.path.isfile(source):
        sys.exit("no such library slide: " + source)
    meta = read_meta(source) or {}
    slug = os.path.splitext(os.path.basename(relpath))[0]
    topic = meta.get("topic") or os.path.dirname(relpath)
    bundle = os.path.join(ASSETS, topic, slug)

    # Slidev drops `src:` targets outside the deck root without warning, so the slide
    # has to live inside the deck. pages/ keeps it out of the main slides.md.
    pages = os.path.join(deck, "pages")
    os.makedirs(pages, exist_ok=True)
    dest = os.path.join(pages, slug + ".md")
    if os.path.exists(dest):
        print("exists, not overwritten: " + dest)
    else:
        shutil.copy2(source, dest)
        print("copied slide  -> " + dest)

    assets = meta.get("assets") or []
    if isinstance(assets, str):
        assets = [assets]
    for asset in assets:
        src = os.path.join(bundle, asset)
        dst = os.path.join(deck, "public", asset)
        if not os.path.isfile(src):
            print("MISSING in library bundle: " + src)
            continue
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        if os.path.exists(dst):
            print("exists, skipped: " + dst)
            continue
        shutil.copy2(src, dst)
        print("copied asset  -> " + dst)

    print("\nAdd this to slides.md where the slide should appear:\n")
    print("---")
    print("src: ./pages/{}.md".format(slug))
    print("---\n")


def main():
    args = sys.argv[1:]
    if not args or args[0] in ("-h", "--help"):
        print(__doc__)
        return
    if args[0] == "index":
        cmd_index()
    elif args[0] == "use" and len(args) == 3:
        cmd_use(args[1], args[2])
    else:
        print(__doc__)
        sys.exit(1)


if __name__ == "__main__":
    main()
